Expose generate_alignment + generate_hgvs_variants_from_alignment functions
mammothbio-os/palamedes pull request #18
Opened 2024-06-27 22:46 UTC by austin-mbs

## Description

Add the following functions for external use
- generate_alignment
- generate_hgvs_variants_from_alignment

## Relevant Links

N/A

### Screenshots & Media

N/A

### Testing

N/A

### Code Flow

N/A

### Edge cases / Breaking Changes / Known Issues

N/A

2024-06-28 15:55 UTC, heuermh commented on README.md
Minor typo, provides &rarr; provide

2024-06-28 15:55 UTC, heuermh commented on palamedes/__init__.py
boolean flags for strategies are not my favorite, could a separate method make a better API?  Or perhaps allow the strategy to be passed in?

2024-06-28 19:40 UTC, mbiokyle29 commented on palamedes/__init__.py
This is existing functionality that is just getting moved so it would be a breaking change to get rid of the flag. Don't think it's worth doing right now, but I am open to a change in a follow up PR if you feel its important. Personally I find the ergonomics of passing a boolean to be a bit better then some string that represents the "method" you want (we'd likely want some kind of constant / enum, etc). If there were a bunch of methods it would make more sense.

2024-06-28 19:47 UTC, mbiokyle29 requested changes
Left a few notes on doc-strings and tests that should not have been moved. If you could also get tests added for the new `generate_hgvs_variants_from_alignment` and populate the PR description with a bit more info, that would be great. Thanks for this!

2024-06-28 19:47 UTC, mbiokyle29 commented on palamedes/__init__.py
> +    - Alignment: Generated via BioPython.PairwiseAligner - (`generate_alignment` for more information)
"See `generate_alignemt` for more information"

2024-06-28 19:47 UTC, mbiokyle29 commented on palamedes/__init__.py
> +
Can you trim this excess white space?

2024-06-28 19:47 UTC, mbiokyle29 commented on palamedes/__init__.py
> +    """
Adding some examples here using the follow format might be nice for the API docs:
```
    .. code-block:: python

        >>> from palamedes import generate_hgvs_variants
        >>> generate_hgvs_variants("PFKISIHL", "TPFKISIH")
        [
            SequenceVariant(ac=ref, type=p, posedit=Pro1extThr-1, gene=None),
            SequenceVariant(ac=ref, type=p, posedit=Leu8del, gene=None),
        ]
```
This is from the doc string for `generate_hgvs_variants`

2024-06-28 19:47 UTC, mbiokyle29 commented on palamedes/__init__.py
> +    """
Since this is public now, can you add some code example to the doc string, using the same block as above?

2024-06-28 19:47 UTC, mbiokyle29 commented on palamedes/__init__.py
> +        )
Thank you for making this error message better!

2024-06-28 19:47 UTC, mbiokyle29 commented on palamedes/test_palamedes.py
> +from palamedes import generate_variant_blocks, generate_alignment
`generate_variant_blocks` is still defined in `align.py`, so the tests for it should stay in there. Only `generate_alignment` was moved.

2024-07-01 18:19 UTC, mbiokyle29 approved these changes
LGTM, thanks!

2024-07-01 21:00 UTC, mbiokyle29 approved these changes

2024-07-01 21:05 UTC, merged